### ISSUE TITLE
Request for license for use in education

### ISSUE THREAD

**Issue by nitrosimon** [rdolbeau/PS2forLitex#1]
Hi,

i would like to use this code in a project at university to use with otherwise fully open source (even free) software and hardware.

I would like permission or a license for it.

THX in advance!

Simon

**Comment by rdolbeau** [comment]
I've added an explicit BSD 2-Clause License, same as Litex itself.

Thanks for your interest :-) It was an early attempt at hardware design, might not be a great example... caveat emptor!
